name: Generate GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: stats-output

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: stats-output
          build_dir: profile-summary-card-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}