name: WakaTime Card

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */12 * * *"

permissions:
    contents: write

jobs:
    update-card:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Generate WakaTime card
              env:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
              run: python scripts/wakatime-card.py

            - name: Update README cache buster
              run: |
                  VERSION=$(date +%s)

                  sed -i -E \
                    's|(assets/wakatime-card\.svg\?v=)[^"]*|\1'"$VERSION"'|g' \
                    README.md

            - name: Commit card
              run: |
                  git config user.name "AryanBaghel-1"
                  git config user.email "albertmit98@gmail.com"

                  git add assets/wakatime-card.svg README.md

                  git diff --cached --quiet || git commit -m "update WakaTime card"

                  git push
